package com.fms.client.common;

public enum FacilityErrorCode {

    BUILDING_ALREADY_EXISTS,
    INSERT_FACILITY_DETAIL_FAILED,
    NAMED_FACILITY_ALREADY_EXISTS,
    INVALID_MAINTENANCE_REQUEST,
    UNABLE_TO_DELETE_REQUEST

}