/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.fms;

import org.junit.Test;
import static org.junit.Assert.*;
import java.sql.Connection;
import com.fms.dal.DBConnection;

public class DBConnectionTest {
    @Test
    public void dbConnectionTest() throws java.sql.SQLException {
        Connection connection = DBConnection.getConnection();

        System.out.println("Connection is: " + connection.toString());
    }
}
