/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.fms;

import static org.junit.Assert.*;

import com.fms.dal.DBConnection;
import java.sql.Connection;
import org.junit.Test;

public class DBConnectionTest {
  @Test
  public void dbConnectionTest() throws java.sql.SQLException {
    Connection connection = DBConnection.getConnection();

    System.out.println("Connection is: " + connection.toString());
  }
}
