package com.fms.domainLayer.common;

public enum FacilityErrorCode {
  BUILDING_ALREADY_EXISTS,
  INSERT_FACILITY_DETAIL_FAILED,
  NAMED_FACILITY_ALREADY_EXISTS,
  INVALID_MAINTENANCE_REQUEST,
  UNABLE_TO_DELETE_REQUEST,
  SCHEDULE_ROOM_MAINTENANCE_FAILED,
  UNABLE_TO_CALCULATE_COST,
  UNABLE_TO_INSERT_HOURLY_RATE
}
