package com.fms.domainLayer.common;

public enum FacilityErrorCode {
  BUILDING_ALREADY_EXISTS,
  INSERT_FACILITY_DETAIL_FAILED,
  NAMED_FACILITY_ALREADY_EXISTS,
  INVALID_MAINTENANCE_REQUEST,
  UNABLE_TO_DELETE_REQUEST,
  SCHEDULE_ROOM_MAINTENANCE_FAILED,
  SCHEDULE_FACILITY_MAINTENANCE_FAILED,
  UNABLE_TO_CALCULATE_COST,
  UNABLE_TO_INSERT_HOURLY_RATE,
  NO_FACILITY_INFORMATION,
  NO_ROOM_FOR_ROOM_MAINTENANCE_REQUEST,
  COULD_NOT_GET_FACILITY_ID_FROM_FACILITY_MAINTENANCE_REQUEST_ID,
  ROOM_CONFLICTS_EXIST
}
